### ISSUE TITLE
POSTGRES_URL environment variable is not set

### ISSUE THREAD

**Issue by Prathamesh-chougale-17** [leerob/next-saas-starter#10]
![image](https://github.com/user-attachments/assets/89f87b0f-be16-4923-9631-833e5d9453cd)

Procedure:
Run pnpm install to install dependencies.
Run pnpm db:setup to initialize the database.
Run pnpm db:migrate to apply migrations.
The error appears indicating that POSTGRES_URL is not set.

.env.local:
POSTGRES_URL=POSTGRES_URL=postgresql://postgres.<database_name>:<database_password>#fDbS@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
STRIPE_SECRET_KEY=sk_test_***************************************************************************************************
STRIPE_WEBHOOK_SECRET=whsec_****************************************************************
BASE_URL=http://localhost:3000
AUTH_SECRET=****************************************************************

While attempting to run database migrations using pnpm db:migrate, I encountered an error stating that the POSTGRES_URL environment variable is not set. The migration script is unable to proceed without this variable.

**Comment by kk7188048** [comment]
In the readme section it is written there you need to set urself .env file with own db url by going to any free db psql provider or local psql database.

**Comment by Prathamesh-chougale-17** [comment]
yep i have filled all the env's but it was not working. so i changed .env.local to .env then it's working now. Thanks for checking my issue
