### ISSUE TITLE
Sign-up & Sign-in forms allow user enumeration attack

### ISSUE THREAD

**Issue by TimMikeladze** [leerob/next-saas-starter#13]
By sending a valid username with an incorrect password, it's possible to determine if a user exists in the app. This is possible on the sign-up form and on the sign-in page.

To reproduce:

- On the sign-in page submit the form with an email of a user that already exists but a wrong password.
- On the sign-up page submit the form with en email of a user that already exists.

https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/03-Identity_Management_Testing/04-Testing_for_Account_Enumeration_and_Guessable_User_Account

![Screenshot 2024-09-17 at 02 40 04](https://github.com/user-attachments/assets/1567cfba-6406-4d3d-8b95-6302f875f157)
![Screenshot 2024-09-17 at 02 40 42](https://github.com/user-attachments/assets/d159bf0f-7eed-4093-bb93-3f67a5e3b974)

**Comment by leerob** [comment]
Good flag, I was thinking about this but didn't get around to it. Might be a good first issue for folks to contribute 😄
