### ISSUE TITLE
Adding Prettier and ESLint to this template

### ISSUE THREAD

**Issue by MichailiK** [leerob/next-saas-starter#15]
Would there be any interest to adding Prettier, as well as ESLint and plugins such as:

- `eslint-plugin-next`
- `eslint-plugin-react`
- `eslint-plugin-react-hooks`
- maybe `eslint-plugin-jsx-a11y`?
- maybe `typescript-eslint`?

To this project? It'd help enforce a code style & alert people of various pitfalls & bad practices that can be encountered.

**Comment by TimMikeladze** [comment]
Perhaps the eslint rules that ship with nextjs out of the box should be used? https://nextjs.org/docs/app/building-your-application/configuring/eslint

**Comment by leerob** [comment]
I don't want to add ESLint or Prettier here – I should be using the default Prettier rules I believe locally.

**Comment by TimMikeladze** [comment]
@leerob any reason why not to add linting?  For example the diff in #51 has a bunch of single quote to double quote changes.
