### ISSUE TITLE
Supabase Setup - Guide

### ISSUE THREAD

**Issue by albertpco** [leerob/next-saas-starter#40]
No idea where to put this but wanted to follow up from twitter since i finally found a few minutes to give this a shot. 
# Quick Setup Guide for next-saas-starter with Supabase

## 1. Clone the Repository

First, clone the repository to your local machine:

```bash
git clone https://github.com/leerob/next-saas-starter
cd next-saas-starter
```

## 2. Install Dependencies

Install all the required dependencies using pnpm:

```bash
pnpm install
```

## 3. Run the Database Setup

Run the following command, and when prompted to choose between a local Postgres instance or a remote one, choose R for remote:

```bash
pnpm db:setup
```

When prompted, select "R" to use a remote Postgres instance.

Copy your Supabase Postgres connection URL from the Supabase dashboard:
- Go to Project Settings > Database > Connection String in Supabase.
- Paste the connection string when prompted.

## 4. Run Database Migrations

Once the database is connected, apply the migrations to set up your schema:

```bash
pnpm db:migrate
```

## 5. Seed the Database (Optional)

If the project includes a seed script for populating initial data, run the following command:

```bash
pnpm db:seed
```

## 6. Start the Development Server

Now you're ready to run the app. Start the development server with:

```bash
pnpm dev
```

Your Next.js app should now be connected to Supabase, and you can access it locally at http://localhost:3000.

**NOTE:** This setup guide does not include authentication configuration.

**Comment by leerob** [comment]
Nice, thank you! I believe this should all be covered in the README 😄

**Comment by albertpco** [comment]
Should be! But just saw that PR so maybe people go brrr through the list without pausing on the local dev.
