### ISSUE TITLE
First time using pnpm 

### ISSUE THREAD

**Issue by SaddamMohsen** [leerob/next-saas-starter#43]
this is the first time i used a pnpm package manager for running this project
so can i run it with yarn or npm 
but this is not the problem 
the problem is after i installed a pnpm then do pnpm install this is working perfectly 
okay when i typed pnpm run dev 
it show this error
Error: Your application tried to access styled-jsx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: styled-jsx (via "styled-jsx\package.json")
so what is the wrong here

**Comment by leerob** [comment]
I am not sure about that, unfortunately I cannot reproduce. You're using the latest version on pnpm?

**Comment by SaddamMohsen** [comment]
> I am not sure about that, unfortunately I cannot reproduce. You're using the latest version on pnpm?

okay thank you
i think this problem is related to yarn and pnpm conflict on my pc

but can i use yarn or npm to run the project

**Comment by leerob** [comment]
You might try uninstalling and reinstalling your package managers, or just use npm or yarn for this!
