### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by gdrxn** [leerob/next-saas-starter#5]
<img width="285" alt="image" src="https://github.com/user-attachments/assets/c2c75668-ef82-48df-89a4-b6df03b5080f">

User is already signed up, but when wants to sign in, it gives this error.

**Comment by younes101020** [comment]
hello, you need to add the AUTH_SECRET environment variable on prod

**Comment by gdrxn** [comment]
Hi, yeah, that was the issue. Thank you. Maybe it would be better to have .env file with needed variables for dev mode. @leerob 

Btw thank you for this starter! I think having template like this and keep maintaining it is huge boost for Next ecosystem and productivity overall. 🙏

**Comment by leerob** [comment]
Appreciate that @gdrxn!

Thank you @younes101020 🙏 https://github.com/leerob/next-saas-starter/pull/6
