### ISSUE TITLE
can't pass the user promise to the userprovider 

### ISSUE THREAD

**Issue by corolair-hazem** [leerob/next-saas-starter#53]
I'am using the latest NextJs version and when i try to implement the auth strategy that you did i always get this error :
Only plain objects, and a few built-ins, can be passed to Client Components from Server Components. Classes or null prototypes are not supported.

is there a work around ?

**Comment by corolair-hazem** [comment]
do i need NextJs canary version for this, or will it work on 14.2.13 ?

**Comment by leerob** [comment]
Correct, you need React 19 (which this template uses).
