### ISSUE TITLE
Team Creation Failure During User Registration ﻿

### ISSUE THREAD

**Issue by jiafei-cat** [leerob/next-saas-starter#61]
When a user registers, the user is successfully added to the users table, but the team creation process is interrupted due to external factors. This results in an error when querying the team. Would it be better to implement this with transactions?
![image](https://github.com/user-attachments/assets/0cee539b-a343-4cf9-aeb6-8903ac5db9db)

**Comment by leerob** [comment]
It's definitely an option! In practice I didn't see this ever happen, but if you want to harden your app, it's a good suggestion
