### ISSUE TITLE
empty string for 'line_items[0][price]' bug with proceeding to pricing and subscription page

### ISSUE THREAD

**Issue by TommyJackson85** [leerob/next-saas-starter#65]
In test mode, after proceeding to one of the payment options I'm getting this error and I think its related to the Stripe library. 

"Error: You passed an empty string for 'line_items[0][price]'. We assume empty values are an attempt to unset a parameter; however 'line_items[0][price]' cannot be unset. You should remove 'line_items[0][price]' from your request or supply a non-empty value."

This is the version of Stripe I'm using = "stripe": "^16.12.0" anyway had this issue before? is there some information I'm missing?

**Comment by leerob** [comment]
I didn't see this issue with my repo so unfortunately can't help out much here. Sorry about that.

**Comment by seyhunak** [comment]
Same issue replicated in my env, as well during pricing endpoint call. @leerob  

Any suggestions?

Backtrace from Stripe Logs:

parameter_invalid_empty - line_items[0][price]
The price field cannot be empty and must reference an existing `price` object id such as: `price: price_xxx`.

Backtrace - Vercel

⨯ Error: You passed an empty string for 'line_items[0][price]'. We assume empty values are an attempt to unset a parameter; however 'line_items[0][price]' cannot be unset. You should remove 'line_items[0][price]' from your request or supply a non-empty value.
    at A.x [as generate] (/var/task/.next/server/chunks/647.js:1:49531)
    at o.toJSON.then.C.message (/var/task/.next/server/chunks/647.js:1:55177) {
  type: 'StripeInvalidRequestError',
  raw: [Object],
  rawType: 'invalid_request_error',
  code: 'parameter_invalid_empty',
  doc_url: 'https://stripe.com/docs/error-codes/parameter-invalid-empty',
  param: 'line_items[0][price]',
  detail: undefined,
  headers: [Object],
  requestId: 'req_bQ4d8752UeNHr3',
  statusCode: 400,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  payment_method_type: undefined,
  setup_intent: undefined,
  source: undefined,
  digest: '2167374297'
}

**Comment by seyhunak** [comment]
Figured out my self,

Upgrading Stripe API contract to the 2024-11-20.acac fixed the problem.

[2024-11-20.acacia](https://docs.stripe.com/upgrades#2024-11-20.acacia)
