### ISSUE TITLE
Payment Gateway Options

### ISSUE THREAD

**Issue by yesbhautik** [leerob/next-saas-starter#76]
It will be great if you add RazorPay and PayU payment gateway for Indian devs. Stripe is no more accepting new accounts from India.

**Comment by leerob** [comment]
Good idea! While I don't plan to add this here, it would be an awesome fork to switch out Stripe

**Comment by yesbhautik** [comment]
We are facing multiple issue in process of integration of RazorPay and PayU for the SaaS stuff. If you can help then it will be very good.
