### ISSUE TITLE
You're importing a component that needs "next/headers". That only works in a Server Component which is not supported in the pages/ directory. Read more: https://nextjs.org/docs/app/building-your-application/rendering/server-components

### ISSUE THREAD

**Issue by poorman** [leerob/next-saas-starter#80]
not sure why it sees as client side file?? 
./src/lib/auth/session.ts:3:1

Ecmascript file had an error
  1 | import { compare, hash } from 'bcryptjs';
  2 | import { SignJWT, jwtVerify } from 'jose';
> 3 | import { cookies } from 'next/headers';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You're importing a component that needs "next/headers". That only works in a Server Component which is not supported in the pages/ directory. Read more: https://nextjs.org/docs/app/building-your-application/rendering/server-components

**Comment by leerob** [comment]
I'm not sure what you've changed from how the template is right now, but I don't see this error.

You're importing or using that session library in `pages/*` somehow or a client component?
